binary-ghc-args:
- -O2
- -threaded
- -ddump-simpl-stats
- -fenable-rewrite-rules
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-unstable
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: haskell-src 1.0.2.0

  Hackage: CCA 0.1.5.2

'
ghc-args:
- -fno-warn-unused-matches
- -fno-warn-unused-binds
- -ddump-simpl-stats
- -fenable-rewrite-rules
excluded-modules:
- src/Examples.hs
