binary-ghc-args:
- -O
- -threaded
- -fenable-rewrite-rules
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-unstable
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: haskell-src 1.0.2.0

  Hackage: th-reify-many 0.1.2

  Hackage: th-orphans 0.8.3

  Hackage: haskell-src-meta 0.6.0.8

  Hackage: text 1.2.0.4

  Hackage: transformers 0.4.2.0

  Hackage: mtl 2.2.1

  Hackage: parsec-extra 0.1.0.5

  Hackage: needle 0.1.0.1

'
ghc-args:
- -fenable-rewrite-rules
excluded-modules:
- src/Examples.hs
