binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.8-unstable
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: monad-parallel 0.7.1.4'
ghc-args:
- -fdefer-type-errors
excluded-modules:
- src/Base.hs
